k6 tests in CI - web3 (#12151)
- add web3 k6 tests to acceptance test workflow

Signed-off-by: Bilyana Gospodinova <bilyana.gospodinova14@gmail.com>

diff --git a/.github/workflows/acceptance.yaml b/.github/workflows/acceptance.yaml
--- a/.github/workflows/acceptance.yaml
+++ b/.github/workflows/acceptance.yaml
@@ -140,6 +140,7 @@ jobs:
               HIERO_MIRROR_TEST_ACCEPTANCE_FEATURE_CONTRACTCALLLOCALESTIMATE: "true"
               HIERO_MIRROR_TEST_ACCEPTANCE_NETWORK: OTHER
               HIERO_MIRROR_TEST_ACCEPTANCE_WEB3_OPCODETRACER_ENABLED: "true"
+              HIERO_MIRROR_TEST_ACCEPTANCE_SKIPENTITIESCLEANUP: "true"
             enabled: true
           web3:
             env:
@@ -152,7 +153,71 @@ jobs:
           echo "Solo cluster setup completed successfully!"
 
       - name: Run acceptance tests
-        run: helm test mirror -n "${SOLO_NAMESPACE}" --logs --filter name=mirror-acceptance --timeout 20m
+        run: |
+          touch output_log.txt
+          helm test mirror -n "${SOLO_NAMESPACE}" --logs --filter name=mirror-acceptance --timeout 20m | tee output_log.txt
+
+      - name: Parse acceptance tests logs and set k6 environment variables
+        if: ${{ matrix.stream-type != 'BLOCK' }}
+        id: log-variables
+        run: |
+          set -ex
+          LOG_FILE="${{ github.workspace }}/output_log.txt"
+
+          declare -A k6Map
+          k6Map["PARENT"]="DEFAULT_CONTRACT_ADDRESS"
+          k6Map["ERC"]="ERC_CONTRACT_ADDRESS"
+          k6Map["ESTIMATE_PRECOMPILE"]="ESTIMATE_PRECOMPILE_CONTRACT"
+          k6Map["PRECOMPILE"]="PRECOMPILE_CONTRACT"
+          k6Map["BOB"]="PAYER_ACCOUNT"
+          k6Map["ALICE"]="ACCOUNT_ADDRESS"
+          k6Map["fungible"]="TOKEN_ADDRESS"
+          k6Map["non_fungible"]="NON_FUNGIBLE_TOKEN_ADDRESS"
+
+          for key in "${!k6Map[@]}"; do
+            value=$(grep -oP "^${key}=(\K.+)$" "$LOG_FILE" | tail -n 1  || true)
+            echo "${key}=${value}" >> $GITHUB_ENV
+          done
+
+      - name: Install k6
+        if: ${{ matrix.stream-type != 'BLOCK' }}
+        uses: grafana/setup-k6-action@ffe7d7290dfa715e48c2ccc924d068444c94bde2 # v1
+
+      - name: Port forward web3
+        if: ${{ matrix.stream-type != 'BLOCK' }}
+        run: |
+          echo "Port forwarding 8080:80"
+          kubectl port-forward "service/mirror-web3" -n mirror 8080:80 &
+
+      - name: Run k6 web3 tests
+        if: ${{ matrix.stream-type != 'BLOCK' }}
+        uses: grafana/run-k6-action@a15e2072ede004e8d46141e33d7f7dad8ad08d9d # v1
+        env:
+          ACCOUNT_ADDRESS: ${{ env.ALICE }}
+          AMOUNT: "0000000000000000000000000000000000000000000000000000000000000001"
+          BASE_URL: "http://127.0.0.1:8080"
+          DEFAULT_CONTRACT_ADDRESS: ${{ env.PARENT }}
+          DEFAULT_DURATION: "3s"
+          DEFAULT_GRACEFUL_STOP: "1s"
+          DEFAULT_VUS: 2
+          ERC_CONTRACT_ADDRESS: ${{ env.ERC }}
+          ESTIMATE_PRECOMPILE_CONTRACT: ${{ env.ESTIMATE_PRECOMPILE }}
+          HTS_CONTRACT_ADDRESS: ${{ env.PRECOMPILE }}
+          KEY_TYPE: "0000000000000000000000000000000000000000000000000000000000000001"
+          NON_FUNGIBLE_TOKEN_ADDRESS: ${{ env.non_fungible }}
+          PAYER_ACCOUNT: ${{ env.BOB }}
+          RUN_COMPLEX_TESTS: "false"
+          RUN_ESTIMATE_TESTS: "false"
+          RUN_MODIFICATION_TESTS: "false"
+          RUN_WITH_VARIABLES: "true"
+          SERIAL_NUMBER: "0000000000000000000000000000000000000000000000000000000000000001"
+          TOKEN_ADDRESS: ${{ env.fungible }}
+          WEB3_TEST_EXCLUDE: "^contractCall(Allowance|ApprovedForAll|BalanceOf|IsFrozen|IsKyc|Receive).*$"
+        with:
+          path: |
+            ./tools/k6/src/web3/apis.js
+          debug: false
+          flags: --quiet
 
       - name: Show Pod Logs on Failure
         continue-on-error: true
@@ -169,7 +234,7 @@ jobs:
           for pod in $(kubectl get pods -n "${SOLO_NAMESPACE}" -o name); do
             if [ -n "$pod" ]; then
               echo "--- Logs for pod: $pod ---"
-              kubectl logs "$pod" -n "${SOLO_NAMESPACE}" --all-containers=true --tail=1000 || echo "Could not get logs for pod $pod"
+              kubectl logs "$pod" -n "${SOLO_NAMESPACE}" --all-containers=true --tail=10000 || echo "Could not get logs for pod $pod"
             fi
           done
 
